HTTP_PORT_NUMBER = ENV.include?("ODATA_PORT") ? ENV["ODATA_PORT"] : 8989
HTTPS_PORT_NUMBER = ENV.include?("ODATA_SSL_PORT") ? ENV["ODATA_SSL_PORT"] : 44300
WEBSERVER = ENV.include?("ODATA_SERVER") ? ENV["ODATA_SERVER"] : 'localhost'
