lib =  File.dirname(__FILE__)

$: << lib + "/ruby_odata/"
require "rubygems"
require "i18n"
require "active_support" # Used for serializtion to JSON
require "active_support/inflector"
require "active_support/core_ext"
require "cgi"
require "faraday_middleware"
require "faraday"
require "nokogiri"
require "bigdecimal"
require "bigdecimal/util"
require "addressable/uri"

require lib + "/ruby_odata/exceptions"
require lib + "/ruby_odata/association"
require lib + "/ruby_odata/property_metadata"
require lib + "/ruby_odata/query_builder"
require lib + "/ruby_odata/class_builder"
require lib + "/ruby_odata/operation"
require lib + "/ruby_odata/resource"
require lib + "/ruby_odata/service"
require lib + "/ruby_odata/helpers"
